#!/usr/bin/env python3
"""gen_udev_rules — boat device-config JSON -> native udev rules + resolved JSON.

Input: a RoboBoat-style boat config (config/crusader.json) that pins devices to
physical USB topology paths (sysfs DEVPATH), e.g.

    "teensy": {"port": ".../usb1/1-2/1-2.2/1-2.2:1.0/tty/ttyACM0", "rate": 115200}

Output:
  1. a udev rules file matching each device by its USB PORT CHAIN
     (KERNELS=="1-2.2:1.0") and creating a stable symlink /dev/crsd-teensy;
  2. a rewritten config JSON with every 'port' replaced by its symlink, so
     consumers open /dev/crsd-teensy directly — no runtime enumeration
     (usbLink.sh) or path string-matching (deviceHelper.findFromId) needed.

Why port-chain matching beats the full DEVPATH string the JSONs carry today:
the platform prefix is NOT stable ("3610000.xhci" vs "bus@0/3610000.usb" across
JetPack versions — compare barco.json vs crusader.json), but the port chain
"1-2.2:1.0" encodes only bus + hub ports, which survive controller renames.
The tradeoff vs serial-number matching is unchanged from the team's current
practice: each device must stay plugged into ITS port. Label the hub ports.

Usage:
  python3 gen_udev_rules.py path/to/crusader.json \
      --rules-out 99-crusader-devpath.rules \
      --json-out crusader_devices.json
Then install with install_udev.sh (it installs every 99-crusader*.rules).

Discover current paths for a new/rewired boat with:
  udevadm info -q property -n /dev/ttyACM0 | grep DEVPATH     (or usbLink.sh)
"""
import argparse
import json
import re
from pathlib import Path

INTERFACE_RE = re.compile(r"^\d+-[\d.]+:\d+\.\d+$")   # e.g. 1-2.4.3:1.0
DEVICE_RE = re.compile(r"^\d+-[\d.]+$")               # e.g. 1-2.4.3


class DevpathError(ValueError):
    pass


def parse_devpath(devpath: str) -> dict:
    """Extract the stable matching keys from a sysfs DEVPATH.

    Returns {"kernels": "<port-chain:iface>", "subsystem": "tty"|"video4linux"}.
    Raises DevpathError on anything that doesn't look like a USB tty/v4l path —
    a silently-wrong rule is worse than no rule.
    """
    segments = [s for s in devpath.split("/") if s]
    interface = None
    for seg in segments:                      # last interface segment wins
        if INTERFACE_RE.match(seg):
            interface = seg
    if interface is None:
        # fall back to the deepest device-level segment (no interface suffix)
        device = None
        for seg in segments:
            if DEVICE_RE.match(seg):
                device = seg
        if device is None:
            raise DevpathError(f"no USB port chain found in {devpath!r}")
        interface = device
    if "/tty/" in devpath:
        subsystem = "tty"
    elif "video4linux" in devpath:
        subsystem = "video4linux"
    else:
        raise DevpathError(f"unsupported subsystem in {devpath!r} "
                           "(expected tty or video4linux)")
    return {"kernels": interface, "subsystem": subsystem}


def symlink_name(device_name: str, prefix: str = "crsd") -> str:
    return f"{prefix}-{device_name.replace('_', '-')}"


def generate(config: dict, prefix: str = "crsd", source_name: str = "config"):
    """Returns (rules_text, resolved_config_dict)."""
    rules = [
        f"# Generated by gen_udev_rules.py from {source_name} -- do not hand-edit;",
        "# re-run the generator after any cabling change (discover new paths with",
        "# usbLink.sh or: udevadm info -q property -n /dev/ttyACM0 | grep DEVPATH).",
        "# Port-chain (KERNELS) matching: device identity = which physical port",
        "# it is plugged into. Keep cabling fixed; label the hub ports.",
        "",
    ]
    resolved = {}
    for name, cfg in config.items():
        if not isinstance(cfg, dict) or "port" not in cfg:
            if isinstance(cfg, dict) and "id" in cfg:
                rules.append(f"# {name}: matched by its own id "
                             f"({cfg['id'] or 'UNSET'}), not a udev tty rule "
                             "(depthai enumerates it; VID rule in "
                             "99-crusader.rules grants permissions)")
                rules.append("")
            resolved[name] = cfg                # pass through untouched
            continue
        info = parse_devpath(cfg["port"])
        link = symlink_name(name, prefix)
        mode = ('MODE="0660", GROUP="dialout"' if info["subsystem"] == "tty"
                else 'MODE="0660", GROUP="video"')
        rules.append(f'# {name}: port chain {info["kernels"]}')
        rules.append(
            f'SUBSYSTEM=="{info["subsystem"]}", KERNELS=="{info["kernels"]}", '
            f'SYMLINK+="{link}", {mode}')
        rules.append("")
        out = dict(cfg)
        out["port"] = f"/dev/{link}"
        out["port_chain"] = info["kernels"]     # provenance for debugging
        resolved[name] = out
    return "\n".join(rules), resolved


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("config", help="boat config JSON (crusader.json format)")
    ap.add_argument("--rules-out", default="99-crusader-devpath.rules")
    ap.add_argument("--json-out", default="crusader_devices.json",
                    help="rewritten config with stable /dev symlinks")
    ap.add_argument("--prefix", default="crsd")
    args = ap.parse_args()

    src = Path(args.config)
    config = json.loads(src.read_text())
    rules, resolved = generate(config, args.prefix, source_name=src.name)

    Path(args.rules_out).write_text(rules + "\n")
    Path(args.json_out).write_text(json.dumps(resolved, indent=4) + "\n")
    print(f"wrote {args.rules_out} and {args.json_out}")
    print("install: sudo ./install_udev.sh   then replug (or udevadm trigger)")
    print("verify:  ls -l /dev/crsd-*")


if __name__ == "__main__":
    main()
