"""sitl_params — build the SITL parameter file from the boat's own baseline.

    python3 -m crusader_sim.sitl_params --out /tmp/crusader_gz.parm

Takes params/working_crusader.params (QGC format, the baseline param_guard and
preflight gate on), keeps only the parameters that shape how the VEHICLE
behaves, and appends config/sitl_overlay.parm.

A WHITELIST, not a blacklist, because the dangerous direction is asymmetric:
a hardware parameter that slips through (an accel offset, a serial protocol, a
battery pin) quietly corrupts the simulated vehicle, while a behaviour parameter
left out shows up at once as "the sim does not do what the boat does" — and
the fix is one line here.
"""
import argparse
import os
import re

from crusader_sim.paths import sim_share, _SRC_REPO

KEEP = re.compile(
    r"^(FRAME_|SERVO[1-4]_|MOT_|ATC_|PSC_|CRUISE_|WP_|TURN_|NAVL1_|LOIT_|PILOT_|"
    r"MODE\d|MODE_CH$|INITIAL_MODE$|SPEED_|ACRO_|MANUAL_|GUID_|RTL_|SAIL_|"
    r"FS_|ARMING_(CHECK|REQUIRE|RUDDER)$|RC\d+_OPTION$|AVOID_|PRX1_TYPE$|"
    # RC1-4 trims, ranges and dead zones: the sticks' calibration. Left out, SITL
    # put its defaults under the boat's sticks (trim 1500, a 30 us steering dead
    # zone where the boat has RC1_DZ 0 and RC1_TRIM 1489), so a small yaw
    # override from the tree's 1489 neutral fell inside the dead zone and the
    # hull never squared up (Task 3 docking, 2026-10-05).
    r"RC[1-4]_(TRIM|MIN|MAX|DZ)$|"
    r"EK3_SRC1_|AHRS_EKF_TYPE$|BAL_|SYSID_THISMAV$|STICK_MIXING$|OA_|"
    # SR0_*: the stream rates the ROS side is built around (ATTITUDE at 30 Hz,
    # telemetry_bridge's docstring). MAVProxy connects to SITL's SERIAL0 as it
    # does to the Pixhawk's USB, and --streamrate=-1 leaves these alone. Left
    # out, SITL's defaults gave /crsd/attitude 1.4 Hz and target_tracker
    # refused every observation as stale (2026-09-29).
    r"SR0_)")


def baseline_path():
    for p in (os.path.join(_SRC_REPO, "params", "working_crusader.params"),
              os.path.join(sim_share(), "..", "..", "..", "..", "src", "rx26_asv",
                           "params", "working_crusader.params")):
        if os.path.isfile(p):
            return os.path.abspath(p)
    raise FileNotFoundError("params/working_crusader.params not found")


def read_qgc(path):
    out = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            parts = line.split()
            if len(parts) >= 4 and not line.startswith("#"):
                out[parts[2]] = parts[3]
    return out


def read_parm(path):
    out = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if line:
                k, v = line.replace(",", " ").split()[:2]
                out[k] = v
    return out


def build(out_path, baseline=None, overlay=None):
    baseline = baseline or baseline_path()
    overlay = overlay or os.path.join(sim_share(), "config", "sitl_overlay.parm")
    base = read_qgc(baseline)
    kept = {k: v for k, v in base.items() if KEEP.match(k)}
    over = read_parm(overlay)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(f"# generated by crusader_sim.sitl_params\n# baseline: {baseline}\n")
        f.write(f"# kept {len(kept)} of {len(base)} baseline params; overlay {overlay}\n")
        for k in sorted(kept):
            f.write(f"{k} {kept[k]}\n")
        f.write("# ---- overlay ----\n")
        for k, v in over.items():
            f.write(f"{k} {v}\n")
    return len(kept), len(base), over


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    kept, total, over = build(a.out)
    print(f"{a.out}: {kept}/{total} baseline params + {len(over)} overlay")


if __name__ == "__main__":
    main()
