"""render — turn a mission_spec tree into something a human or a library reads.

Stdlib only, deliberately (see mission_spec's docstring). Three outputs:

  ascii()  a paste-into-Slack tree for review
  xml()    BehaviorTree.CPP 4 XML — loadable by BT.CPP and openable in Groot2
  dot()    graphviz, for a document

The XML is GENERATED, never hand-edited. A hand-maintained XML beside a
hand-maintained Python tree is two sources of truth that agree only until
someone is in a hurry.
"""
from . import mission_spec as ms

_GLYPH = {ms.SEQUENCE: "-->", ms.FALLBACK: "?->", ms.FORCE_SUCCESS: "[ok]",
          ms.RETRY: "[re]", ms.MISSION: "( )", ms.CONDITION: "<?>"}


def _label(node):
    if node.kind == ms.MISSION:
        return "{} {}  action={}".format(_GLYPH[node.kind], node.name,
                                         node.attrs.get("action", "?"))
    if node.kind == ms.RETRY:
        return "{} retry x{}".format(_GLYPH[node.kind],
                                     node.attrs.get("num_attempts", "?"))
    if node.kind == ms.CONDITION:
        note = node.attrs.get("note", "")
        return "{} {}{}".format(_GLYPH[node.kind], node.name,
                                "  ({})".format(note) if note else "")
    return "{} {}".format(_GLYPH[node.kind], node.name)


def ascii(root, unicode_ok=True):
    """Box-drawing tree. Reads top-to-bottom as execution order.

    unicode_ok=False swaps the box-drawing characters for plain ASCII. That is
    not cosmetic: a Windows console at cp1252 renders the unicode ones as
    mojibake, and a review artefact nobody can read is a review that does not
    happen. print_tree.py decides from the real stdout encoding.
    """
    last_c, mid_c, blank, bar = (("└── ", "├── ",
                                  "    ", "│   ") if unicode_ok else
                                 ("`-- ", "|-- ", "    ", "|   "))
    lines = [_label(root)]

    def rec(node, prefix):
        kids = node.children
        for i, c in enumerate(kids):
            last = i == len(kids) - 1
            lines.append(prefix + (last_c if last else mid_c) + _label(c))
            rec(c, prefix + (blank if last else bar))

    rec(root, "")
    return "\n".join(lines)


def _esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def xml(root, tree_id="CrusaderRun"):
    """BehaviorTree.CPP 4 XML.

    Mission leaves become <SafePassage action_name="..."/> — a node the C++ side
    registers as a RosActionNode, so the action name stays a PORT rather than
    being compiled in. That is what lets this file and crusader_params.yaml be
    the only two places an action name appears.
    """
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<!-- GENERATED by crusader_mission/tree/render.py. Do not edit: edit',
           '     mission_spec.build() and regenerate with',
           '       python3 tools/scripts/print_tree.py --xml -o <file>          -->',
           '<root BTCPP_format="4" main_tree_to_execute="{}">'.format(tree_id),
           '  <BehaviorTree ID="{}">'.format(tree_id)]

    def rec(node, indent):
        pad = "  " * indent
        if node.kind == ms.MISSION:
            out.append('{}<{} name="{}" action_name="{}"/>'.format(
                pad, _bt_leaf_id(node), _esc(node.name),
                _esc(node.attrs.get("action", ""))))
            return
        if node.kind == ms.CONDITION:
            out.append('{}<{} name="{}"/>'.format(pad, _bt_leaf_id(node),
                                                  _esc(node.name)))
            return
        if node.kind == ms.RETRY:
            open_tag = '{}<RetryUntilSuccessful num_attempts="{}">'.format(
                pad, node.attrs.get("num_attempts", 1))
            close = "{}</RetryUntilSuccessful>".format(pad)
        else:
            tag = {ms.SEQUENCE: "Sequence", ms.FALLBACK: "Fallback",
                   ms.FORCE_SUCCESS: "ForceSuccess"}[node.kind]
            open_tag = '{}<{} name="{}">'.format(pad, tag, _esc(node.name))
            close = "{}</{}>".format(pad, tag)
        out.append(open_tag)
        for c in node.children:
            rec(c, indent + 1)
        out.append(close)

    rec(root, 2)
    out += ["  </BehaviorTree>", "</root>"]
    return "\n".join(out)


def _bt_leaf_id(node):
    """The C++/Python node ID a leaf registers under: safe_passage -> SafePassage.

    Just an identifier the runtime registers a class against — nothing here
    parses it. CamelCase so the XML reads like the task list it is.
    """
    return "".join(part.capitalize() for part in node.name.split("_"))


def dot(root, name="crusader_run"):
    """Graphviz. `dot -Tpng` or `dot -Tsvg` — pydot is already in the container."""
    shape = {ms.SEQUENCE: "box", ms.FALLBACK: "diamond",
             ms.FORCE_SUCCESS: "octagon", ms.RETRY: "octagon",
             ms.MISSION: "ellipse", ms.CONDITION: "parallelogram"}
    lines = ["digraph {} {{".format(name), '  rankdir=TB;',
             '  node [fontname="monospace" fontsize=10];']
    ids = {}
    for i, (node, _d, _p) in enumerate(ms.walk(root)):
        ids[id(node)] = "n{}".format(i)
        lines.append('  {} [label="{}" shape={}];'.format(
            ids[id(node)], _esc(_label(node)).replace('"', "'"),
            shape[node.kind]))
    for node, _d, parent in ms.walk(root):
        if parent is not None:
            lines.append("  {} -> {};".format(ids[id(parent)], ids[id(node)]))
    lines.append("}")
    return "\n".join(lines)
